### ISSUE TITLE
Do we have to add void main(String args[]) to the TestFiles or the CUT?

### ISSUE THREAD

**Issue by haydenych** [CastleLab/COMP5111-Spring2022-Student-Assignments#3]
It seems both the randoop generated test files and the CUT does not have a main function. But in the soot tutorial given, we have to look for the return statement in main and snip some code before it ends to report the results.

I'm quite unfamiliar with the paths and setups and I'm still struggling in passing some sanity checks. From my understanding, in the sample, we use soot to generate a modified .class file and execute that modified .class file. So in our assignment, is it similar that we have to snip code and modify Subject.class? Then, invoke the modified Subject.class through executing the generated test cases?

**Comment by maybeLee** [comment]
Indeed, both the test suite generated by randoop and the CUT do not have the main function as they do not encourage directly executing the file to initiate the program, instead, they provide the public class and public method for us to access the code.

Your understanding is correct, to invoke the modified `Subject.class` through executing the generated test cases, we are using the `Junit.run(testClass)` method to do it instead of directly running the `Subject.class`.
